name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test User Service
        run: |
          cd user-service
          docker build -t user-service .
          # If you add tests later, run them here:
          docker run --rm user-service python -m unittest discover || echo "No tests found"
          cd ..

      - name: Build and Test Order Service
        run: |
          cd order-service
          docker build -t order-service .
          docker run --rm order-service python -m unittest discover || echo "No tests found"
          cd ..

      - name: Build Docker Compose Services
        run: docker-compose build

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          sleep 20
          docker-compose down
